baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Bible Study"
enableGitInfo = true

[module]
  proxy = "direct"

  [[module.imports]]
    path = "github.com/google/docsy"

[params]
  offlineSearch = true