baseURL = ""
languageCode = "es"
title = "Bible Study"
enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
summaryLength = 0

[module]
  proxy = "direct"

  [[module.imports]]
    path = "github.com/google/docsy"

[params]
  offlineSearch = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
